version: 2.1
aliases:
- &app_workspace_dir  ~/pollyDocs

defaults: &defaults
  working_directory: *app_workspace_dir
  docker:
    - image: cimg/python:3.9
      environment:
        APP_DIR: *app_workspace_dir

jobs:
  Build: &Build
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Installing all Dependencies
          command: |
            pip install 'jinja2==3.0.0'
            pip install 'mkdocs==1.3.0'
            pip install 'mkdocs-material==8.5.10'
            pip install 'mkdocstrings[python]'
            pip install 'mkdocs-multirepo-plugin'
      - run:
          name: convert markdown to html
          command: |
            ls
            export PYTHONPATH=$(pwd)
            mkdocs build --verbose
            ls
      - persist_to_workspace:
          root: ~/.
          paths: .
  Deploy: &Deploy
    <<: *defaults
    parameters:
      AWS_CI_BUCKET:
        type: string
        default: TEST_DOC_BUCKET
    steps:
      - attach_workspace:
          at: ~/.
      - run:
          name: Installing Dependencies
          command: |
            pip install awscli
      - run:
          name: Configuring aws Credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile misc
            aws configure set aws_secret_access_key $AWS_SECRET_KEY --profile misc
      - run:
          name: Store to bucket
          command: |
            cd site 
            aws s3 sync . s3://$<< parameters.AWS_CI_BUCKET >> --profile misc 

  list_files:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install tree
          command: sudo apt-get update && sudo apt-get install -y tree
      - run:
          name: List directory structure
          command: tree -a -L 5

  testdocs_build:
    <<: *Build
  testdocs_deploy:
    <<: *Deploy
  docs_build:
    <<: *Build
  docs_deploy:
    <<: *Deploy

workflows:
  main:
    jobs:
      - testdocs_build:
          filters:
            branches:
              only:
                - develop
                - ftr/polly-py-fix

      - list_files:
          requires:
            - testdocs_build
          filters:
            branches:
              only:
                - develop
                - ftr/polly-py-fix
          # Run always, even if testdocs_build fails
          conditional: always()
          
      - testdocs_deploy:
          context: polly-docs
          requires:
            - testdocs_build
          filters:
            branches:
              only:
                - develop
                - ftr/polly-py-fix

      - docs_build:
          filters:
            branches:
              only:
                - master
          
      - docs_deploy:
          AWS_CI_BUCKET: DOC_BUCKET
          context: polly-docs
          requires:
            - docs_build
          filters:
            branches:
              only:
                - master
          
